### ISSUE TITLE
iOS 14 User logout does not erase session

### ISSUE THREAD

**Issue by pmmlo** [parse-community/Parse-Swift#44] opened 2020-12-30 22:06 UTC
Hi All - Wanted to check if I am having an implementation issue.  I have tried calling logout both synchronously and asynchronously.  No trouble removing the keychain object, but the session object in database persists.

Anybody having this issue in iOS 14?

**Comment by cbaker6** [comment] 2020-12-30 22:08
By database do you mean still exists on the Parse server?

**Comment by pmmlo** [comment] 2020-12-30 22:28
> By database do you mean still exists on the Parse server?

Yup.

**Comment by cbaker6** [comment] 2020-12-30 22:31
Thanks for filing the issue! I think this is a bug in the SDK. I believe I know where the problem is.

**Comment by pmmlo** [comment] 2020-12-30 22:31
> Thanks for filing the issue! I think this is a bug in the SDK. I believe I know where the problem is.

Got it!  Thanks @cbaker6.  Your PRs are always on point.  Love the rotating keys in parse-server.

**Comment by cbaker6** [comment] 2020-12-30 23:05
> Your PRs are always on point. Love the rotating keys in parse-server.

appreciate you 🙏🏾

**Comment by pmmlo** [comment] 2020-12-31 00:01
@cbaker6 Thanks for the quick fix.  Would have taken me a long time to figure out the updated API endpoint.  Cheers!

**Comment by cbaker6** [comment] 2020-12-31 15:01
No problem @pmmlo thanks for reporting! How do you like using the framework so far (pros/cons)? Also, are you coming from the objective-c iOS SDK? If so, any challenges, things you like better/worse?

Of course, let us know if you find any other issues and if you find something you want to tackle, open a PR and we can help.

**Comment by pmmlo** [comment] 2020-12-31 18:15
I actually haven't used Parse+Objective-C SDK since the pre-acquisition days and the initial transition to an open source project.  I believe there wasn't an open source SDK at that time, so I wrote my own wrapper around the web API.  So, I can't speak much to the comparison, but skimming through both SDKs, they look like a nearly direct port.

Overall, I think Parse+Open Source is excellent.  I mostly use SwiftUI with the changing times, unless I need lower-level.

These are just initial thoughts from my short use.
Pros:
- SPM (what made me use Parse-Swift over Parse-SDK-iOS)
- Plans for integrated Livequery
- Very straightforward open source contribution.

Cons:
- No Livequery.

**Comment by cbaker6** [comment] 2021-01-01 04:39
The public parts of the framework are made to look a little similar to the objective-c one, but they are only minor pieces that have been ported (Keychain and FileManager come to mind). Hopefully the similarity of the public parts makes it easier to use. Under the hood, Parse-Swift is a lot different from it’s counterpart.

**Comment by cbaker6** [comment] 2021-01-01 13:29
Opening this back up. The linked PR fixing the bug will close it once it’s merged

**Comment by pmmlo** [comment] 2021-01-03 08:04
@cbaker6 I had a little time to dig into Parse-Swift's query syntax.  I think the QueryConstraint encoder methods are powerful, more explicit, manageable and extensible.

On initial thought, I think QueryConstraint methods are overall better than passing arguments.  It's been a number of years, but I recall constraints being passed as arguments.  This really made it difficult to extend complex compound queries and arguably, readability suffered.

This choice of making QueryConstraint methods wrap encoders is definitely more explicit and seems to be very extensible as new cases arise.  I think one of the downsides of this new conceptual choice is a loss of parity with the other Parse SDKs, so the associated challenges have to be balanced.

I did have one question: do you think we should potentially create a public init for the QueryConstraint struct, so end users can wrap their own methods around the encoder rather than having to wrap the methods?  Then we could call something like this:
````
let query = GameScore.query(QueryConstraint(key: "score", value: 0, comparator: Comparator.greatherThanOrEqualTo))

query.find(callbackQueue: .main) { results in
    switch results {
    case .success(let scores):
        if scores.count >= 1 {
            scores.forEach { score in
                print("\(score)")
            }
        }
    case .failure(let error):
        print("Error querying: \(error)")
    }
}
````

Just a thought to give developers another syntax option, and allow them to write their own methods that directly wrap the encoder, as needed (rather than contributors writing all permutations).

I may end up thinking this is a dumb idea later but wanted to share while I'm working with Parse Swift.

Not sure if you wrote it, but very well-written IMO.

**Comment by cbaker6** [comment] 2021-01-03 12:57
Thanks looking and taking advantage of the framework! Flo started the project and left a strong foundation. My goal has been to stick with (as much as possible) his suggestions in this comment https://github.com/parse-community/Parse-Swift/issues/3#issuecomment-328351357

Some relevant points he made are:

> The guidelines are quite simple, I want to make the SDK as less intrusive as possible, as you may have noticed, pretty much every functionality is coded as protocols.

> Backwards compatibility/in-place replacement is not a goal, this is a new SDK with a new philosophy. 

Of course, this relieves this SDK of the restrictions of the other SDKs, but introduces a learning curve for experienced parse devs.

As you’ve mentioned, `Query` works differently. It looks like you already know to use them, but I’ll leave some examples for those who find this later https://github.com/parse-community/Parse-Swift/blob/3f1c897c9b9ddaacaf42e8888131d9059f1d73c0/ParseSwift.playground/Pages/7%20-%20GeoPoint.xcplaygroundpage/Contents.swift#L59-L76

Or like this: https://github.com/parse-community/Parse-Swift/blob/3f1c897c9b9ddaacaf42e8888131d9059f1d73c0/ParseSwift.playground/Pages/7%20-%20GeoPoint.xcplaygroundpage/Contents.swift#L118-L133

To your question: 

> I did have one question: do you think we should potentially create a public init for the QueryConstraint struct, so end users can wrap their own methods around the encoder rather than having to wrap the methods?

I’m not sure, but maybe I don’t understand the usecases for it. How do you envision this making it easier?

**Comment by pmmlo** [comment] 2021-01-03 19:27
Thanks for the examples!  I was looking at the source to figure out how queries work.

> > I did have one question: do you think we should potentially create a public init for the QueryConstraint struct, so end users can wrap their own methods around the encoder rather than having to wrap the methods?
> 
> I’m not sure, but maybe I don’t understand the usecases for it. How do you envision this making it easier?

The reason why I asked was because I couldn't figure out how to query by Pointers.  It seems like in the Obj-C SDK you can simply do an equals query, something like this:

```
let playerPointer = Player(objectId: X) // From separate struct
let query = GameScore.query("lastScorer" == playerPointer) // Let's assume GameScore has a pointer to Player called lastScorer.
query.find { results in
...
```

If QueryConstraints were public, we could do something like this:
```
public func equalsPointer(key: String, value: Pointer) -> QueryConstraint {
    return QueryConstraint(key: key, value: value, comparator: .equals)  // This encodes to $eq for the API via enum
}

let playerPointer = Player(objectId: X)
let query = GameScore.query(equalsPointer(key: "lastScorer", value: playerPointer))
query.find { results in
...
```

**Closed** 2021-01-04 03:34 UTC

**Comment by cbaker6** [comment] 2021-01-04 04:16
What happens when you try your first example? Does it not compile or is it the results from the query wrong?

**Comment by pmmlo** [comment] 2021-01-04 04:37
> What happens when you try your first example? Does it not compile or is it the results from the query wrong?

Compiles.  Succeeds without issue, but cannot find the object.  Always `success([])`.

**Comment by cbaker6** [comment] 2021-01-04 04:44
What about the with latest on the `main` that was just merged? I suspect the older versions of Query were going through the `ParseEncoder`, treating them as `ParseObjects` and removing the objectId of the Pointer before it got to the server. I think I switched to not skipping keys for queries in the latest merged.

**Comment by cbaker6** [comment] 2021-01-04 04:48
If that doesn’t work, can you submit a PR and add an example test case to https://github.com/parse-community/Parse-Swift/blob/main/Tests/ParseSwiftTests/ParseQueryTests.swift

**Comment by pmmlo** [comment] 2021-01-04 05:00
Sorry called away for a moment.  No luck, but the update looks really good.  Thanks for contributing.  I'll try to dig into my issue later and see if I can contribute a fix.  Cheers!

**Comment by pmmlo** [comment] 2021-01-07 18:43
Ok, so it turns out I needed to query the pointer by the objectId.  Makes sense.  Example just in case someone stumbles onto this issue.

```
// let playerPointer = Player(objectId: X) // <-- DOES NOT WORK
let playerPointer = X // <-- This works.  X is the PlayerPointer object objectId
let query = GameScore.query("lastScorer" == playerPointer) // Let's assume GameScore has a pointer to Player called lastScorer.
query.find { results in
...
```
